### ISSUE TITLE
NG Input: Left/Right scroll

### ISSUE THREAD

**Issue by elstoc** [dterrahe/darktable#11]
When assigning a shortcut to mouse scroll, it is possible to scroll left/right as well as up/down. In this scenario the controls are inverted: left scroll pushes the slider to the right and vice versa.

Tested using two-finger scroll on a touchpad (Logitech K400+).

Ref: darktable-org#8078

**Comment by dterrahe** [comment]
Hadn't noticed. This might be an X or gtk internal translation that I need to look into. If however I can distinguish this situation, I would think it should be separately mappable.

**Comment by dterrahe** [comment]
The touchpad now has an up/down ("scroll") direction and left/right ("pan") direction. The double-fingered scroll is mapped by X to the same event as a mouse wheel scroll. To me, it feels like the direction is incorrectly inverted, but unless we want to deal with input events at a lower level (I don't!) there isn't much I can do about I think.

Let me know how this works for you. On my laptop, swiping from left to right on the touchpad now moves a mapped slider to the right. For vertical moves, you could experiment with defining a fallback for "value" that assigns speed=-1 to "scroll". But again, this would apply to both touchpad and mousewheel "scrolls".

I'd also love to hear from Mac users!

**Comment by dterrahe** [comment]
No feedback, so I assume this is no longer an (high-priority) issue. Otherwise please refile in main repo.
