### ISSUE TITLE
double click on shortcut tab strange behavior

### ISSUE THREAD

**Issue by AlicVB** [dterrahe/darktable#13]
If I double-click on a row in the shortcut tab (the top tree view in the shortcut tab of the pref dialog) it select the row, but : 
1. no idea how to escape from here : 'esc' key close the pref dialog entirely ; not possible to click outside, even on the close button of the pref dialog... once understood, we are somehow "forced" to define a new shortcut which is "added" and not replace the selected one
2. if I press backspace or enter, it propose to remove a shortcut... but the good one (and not the same between enter and backspace). Removing with backspace seems natural. not so much with enter ;)

If I understand the idea, maybe we can detect a click-doubleclick outside the row which is not a shortcut definition (not key...) and deselect the row in this case ?

Side question : I've not found a way to delete shortcut (the good one)... but I just start to test ;)

**Comment by dterrahe** [comment]
You are right; not at all user friendly at the moment.

If you hold a key longer than the long-click timeout (and not combine it with a move or scroll) it is an invalid shortcut. So if you do that _while_ in shortcut definition mode, the mode gets cancelled without any shortcut being assigned.

I will implement a better way, of course (or multiple ways)! Hard to assign priorities for all the stuff that still needs/wants to be done!

Also will capture Esc so it can be assigned and not cancel the dialog. This has some overlap with #6.

If you try to assign the same shortcut twice (to the same action) it asks if you want to delete it. So for now that is the only official way to delete a shortcut :-) I'll implement deleting by selecting (single click) a shortcut and pressing Del/Backspace.

**Comment by AlicVB** [comment]
> I will implement a better way, of course (or multiple ways)! Hard to assign priorities for all the stuff that still needs/wants to be done!

no problem, take your time :) I perfectly know how you may feel at the moment (I remember last year with my lighttable full rewrite)
just take all this issues as reminders of things not to forget at the end ;)
