### ISSUE TITLE
NG Input: Disable shortcuts while setting up shortcuts

### ISSUE THREAD

**Issue by elstoc** [dterrahe/darktable#3]
This may be negated by #2 but when the user has clicked on the 'create shortcut' button, it should not be possible to **execute** any of the other defined shortcuts - they should all be temporarily disabled. Currently I can execute any shortcut while hovering over a widget that cannot have a new shortcut assigned to it.

Ref: darktable-org#8078

**Comment by dterrahe** [comment]
That could be considered a feature... at least I find that while remapping on the fly I don't really need to leave mapping mode _and_ can immediately test (and fix if needed) a mapping I just set up. The widget that just got mapped temporarily switches to unmappable mode to make this possible (you need to move away and back to map it again or to remove the mapping).

But of course I see your point that for newer users it could be confusing/dangerous.

Let's see if people would like to keep this as an option for power users (with a pref defaulting to off) or if it should be disabled for everybody.
